# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Utern < Formula
  desc "Multi group and stream log tailing for AWS CloudWatch Logs"
  homepage "https://github.com/khulnasoft-lab/utern"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/khulnasoft-lab/utern/releases/download/v0.1.0/utern_0.1.0_darwin_amd64.zip"
      sha256 "61244bed27086245d43ddfa5f7d5bacfb5020ff1429f8cda1c4f7e87b1f0f668"

      def install
        bin.install Dir['utern']
      end
    end
    on_arm do
      url "https://github.com/khulnasoft-lab/utern/releases/download/v0.1.0/utern_0.1.0_darwin_arm64.zip"
      sha256 "e33ffe28639b07b5a96a41ac4e9d7b00f3187f99847b3910db7e1e862c282aaf"

      def install
        bin.install Dir['utern']
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khulnasoft-lab/utern/releases/download/v0.1.0/utern_0.1.0_linux_amd64.zip"
        sha256 "7e678402b49e49a384d98141cfa3bc1d920f279907424a562cfca273c6c747e2"

        def install
          bin.install Dir['utern']
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/khulnasoft-lab/utern/releases/download/v0.1.0/utern_0.1.0_linux_arm64.zip"
        sha256 "887390d3f6167c0847039e746eb2b2684077763815389a8d4f67470b9a0a2949"

        def install
          bin.install Dir['utern']
        end
      end
    end
  end

  test do
    system "#{bin}/utern"
  end
end
